/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.placeholder.PlaceHolder;
import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class daftar extends javax.swing.JFrame {

    /**
     * Creates new form daftar
     */
    public daftar() {
        initComponents();
        PlaceHolder holder1 = new PlaceHolder(username, "Username");
        PlaceHolder holder2 = new PlaceHolder(passwo, "Password");
        PlaceHolder holder3 = new PlaceHolder(nama, "Nama");
        PlaceHolder holder4 = new PlaceHolder(email, "Email");
        PlaceHolder holder5 = new PlaceHolder(noTelp, "Nomor telepon");
        PlaceHolder holder6 = new PlaceHolder(noRek, "No Rekening");
        PlaceHolder holder7 = new PlaceHolder(noKtp, "Nomor KTP");
        PlaceHolder holder8 = new PlaceHolder(namaRek, "Nama Rekening");
    }
    
    public void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom Ini Hanya Bisa Memasukan Karakter Angka");
        }
    }
    
    public void klikDaftar(ActionListener action){
        btnDaftar.addActionListener(action);
    }
    
    public void klikKembali(ActionListener action){
        btnKembali.addActionListener(action);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        passwo = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        noKtp = new javax.swing.JTextField();
        noRek = new javax.swing.JTextField();
        namaRek = new javax.swing.JTextField();
        btnDaftar = new javax.swing.JButton();
        boxBank = new javax.swing.JComboBox<>();
        jenisK = new javax.swing.JComboBox<>();
        noTelp = new javax.swing.JTextField();
        role = new javax.swing.JComboBox<>();
        tglLahir = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        btnKembali.setBackground(new java.awt.Color(204, 204, 204));
        btnKembali.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("< Kembali");
        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setOpaque(true);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buat akun baru untuk menikmati berbagai fitur !");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 250, 40));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 250, 40));

        passwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwoActionPerformed(evt);
            }
        });
        jPanel1.add(passwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 250, 40));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 250, 40));

        noKtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noKtpKeyTyped(evt);
            }
        });
        jPanel1.add(noKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 250, 40));

        noRek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noRekKeyTyped(evt);
            }
        });
        jPanel1.add(noRek, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 190, 40));
        jPanel1.add(namaRek, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 250, 40));

        btnDaftar.setBackground(new java.awt.Color(102, 102, 255));
        btnDaftar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar.setText("Daftar");
        btnDaftar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDaftar.setBorderPainted(false);
        btnDaftar.setContentAreaFilled(false);
        btnDaftar.setOpaque(true);
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 250, 40));

        boxBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bank :", "BRI", "BNI", "BCA", "BTN", "" }));
        jPanel1.add(boxBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 60, 40));

        jenisK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Kelamin", "Laki-laki", "Perempuan" }));
        jenisK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKActionPerformed(evt);
            }
        });
        jPanel1.add(jenisK, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 100, 40));

        noTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpActionPerformed(evt);
            }
        });
        noTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noTelpKeyTyped(evt);
            }
        });
        jPanel1.add(noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 250, 40));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daftar sebagai:", "Pemilik Ukm", "Penyumbang" }));
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 110, 40));

        tglLahir.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(tglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 250, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bis.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -3, 830, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwoActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void noTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpActionPerformed

    private void jenisKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisKActionPerformed

    private void noKtpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKtpKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_noKtpKeyTyped

    private void noTelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noTelpKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_noTelpKeyTyped

    private void noRekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noRekKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_noRekKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxBank;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenisK;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField namaRek;
    private javax.swing.JTextField noKtp;
    private javax.swing.JTextField noRek;
    private javax.swing.JTextField noTelp;
    private javax.swing.JPasswordField passwo;
    private javax.swing.JComboBox<String> role;
    private com.toedter.calendar.JDateChooser tglLahir;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    public JTextField getEmail() {
        return email;
    }

    public JTextField getNama() {
        return nama;
    }

    public JTextField getNamaRek() {
        return namaRek;
    }

    public JTextField getNoKtp() {
        return noKtp;
    }

    public JTextField getNoRek() {
        return noRek;
    }

    public JPasswordField getPasswo() {
        return passwo;
    }

    public JTextField getUsername() {
        return username;
    }

    public JComboBox<String> getBoxBank() {
        return boxBank;
    }

    public JComboBox<String> getJenisK() {
        return jenisK;
    }

    public JTextField getNoTelp() {
        return noTelp;
    }

    public JComboBox<String> getRole() {
        return role;
    }

    public String getTanggal() {
        String tampilan ="yyyy-MM-dd" ; 
        SimpleDateFormat fm = new SimpleDateFormat(tampilan); 
        String tanggal = String.valueOf(fm.format(tglLahir.getDate()));
        return tanggal;
    }
    
}
